spring:
  application:
    name: jader
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/jader_db
    username: root
    password: root_password
  jpa:
    show-sql: true
logging:
  level:
    root: DEBUG
